import type { Capability } from '../types';
import { StatusBadge } from './StatusBadge';

const capabilities: Capability[] = [
  {
    capability: 'Compact binary event profile',
    status: 'implemented',
    evidence: 'Fixed-size PoWV-SBD laboratory packet and canonical unsigned body.',
  },
  {
    capability: 'ECDSA device verification',
    status: 'implemented',
    evidence: 'P-256 verification over the received unsigned bytes.',
  },
  {
    capability: 'Replay protection',
    status: 'implemented',
    evidence: 'Device/event uniqueness with retry-safe in-flight handling.',
  },
  {
    capability: 'Physical Urano acquisition',
    status: 'experimental',
    evidence: 'Serial host bridge and configurable HTTP delivery to an ESP32 endpoint.',
  },
  {
    capability: 'MQTT/TLS and RS-485 transport',
    status: 'roadmap',
    evidence: 'Transport profiles are planned and are not claimed by this console.',
  },
  {
    capability: 'Public-chain tokenization',
    status: 'roadmap',
    evidence: 'No token transaction is generated by the current public application.',
  },
];

export function CapabilityMatrix() {
  return (
    <div className="capability-list">
      {capabilities.map((item) => (
        <article className="capability" key={item.capability}>
          <div>
            <h3>{item.capability}</h3>
            <p>{item.evidence}</p>
          </div>
          <StatusBadge state={item.status} />
        </article>
      ))}
    </div>
  );
}

